apiVersion: v1
kind: Pod
metadata:
  name: proto-pod
spec:
  nodeSelector:
    usedby: prototyping
  containers:
  - name: nextflow
    # image: davidfrantz/force:3.10.04
    # image: nextflow/nextflow:26.04.0
    image: friedricht/nf-force:latest
    imagePullPolicy: Always
    command:
      - /bin/sh
      - "-c"
      - "sleep infinity"
    workingDir: /work-dir/nf-work
    env:
    - name: NXF_WORK
      value: /work-dir/nf-work
    - name: NXF_ANSI_LOG
      value: 'false'
    volumeMounts:
      - mountPath: /work-dir
        name: work
      - mountPath: /data
        name: trends-data
    securityContext:
      runAsUser: 0
    resources:
      requests: 
        memory: 3G
  serviceAccountName: la-nextflow
  volumes:
  - name: work
    persistentVolumeClaim:
      claimName: ceph-data
  - name: trends-data
    persistentVolumeClaim:
      claimName: trends-data
  securityContext:
    runAsUser: 0
